development:
  adapter: postgresql
  database: example
  encoding: utf8
  host: localhost
  port: 5432
  username: postgres
  password: postgres
production:
  adapter: postgresql
  database: example
  encoding: utf8
  host: localhost
  port: 5432
  username: postgres
  password: postgres
